# version: '3.8'

services:
    
    #################################################################
    #                            WEB APP                            #
    #################################################################
    backend:
        image: django:trns
        container_name: backend
        build:
            context: ./srcs/api/
        volumes:
            - ./srcs/api:/var/www
            - static_files:/var/www/static/
        networks:
            - transcendance_net
            - elk
        ports:
            - 8000:8000
        env_file:
            - ./srcs/api/.env
        environment:
            - PROD=false
        restart: on-failure

    frontend:
        image: frontend:trns
        build: ./srcs/frontend
        container_name: nextJs
        volumes:
            - ./srcs/frontend/src/:/app/src/
        depends_on:
            - backend
        networks:
            - transcendance_net
        env_file:
            - ./srcs/frontend/.env
        restart: on-failure

    
    nginx:
        image: ngnix:trns
        container_name: nginx
        build:
            context: ./srcs/nginx/
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - static_files:/usr/share/nginx/html/staticfiles/
        networks:
            - transcendance_net
        depends_on:
            - backend
            - frontend
        restart: always
    #################################################################


volumes:
    postgres_data:
    vault_creds:
        name: vault_creds
    es_data:
    static_files:

networks:
    transcendance_net:
    elk:
